# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170622_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='creted',
            new_name='created',
        ),
    ]
