# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productinbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='session_key',
            field=models.CharField(default='', max_length=128),
        ),
    ]
